Name: PYTHON_Lv1
IconPath: dekat.png
SoundPath: dekat.wav
Description: |
    Equipe de super Python niveau 1
BrainsPackage: teams.python_level_1
ScriptImplementation: python
AgentsBrainClasses:
    WarBase: WarBase.py
    WarExplorer: WarExplorer.py
    WarRocketLauncher: WarRocketLauncher.py
    WarKamikaze: WarKamikaze.py
    WarEngineer: WarEngineer.py
    WarTurret: WarTurret.py
    WarTools: WarTools.py